### ISSUE TITLE
Rails 8 Support

### ISSUE THREAD

**Issue by JuanMiguelGM** [wrapbook/flipper-notifications#10]
Hi, when trying to upgrade to Rails 8,  I get the following issue
```
Because rails >= 8.0.0 depends on activesupport = 8.0.0
  and every version of flipper-notifications depends on activesupport ~> 7.0,
  rails >= 8.0.0 is incompatible with flipper-notifications >= 0.
So, because Gemfile depends on rails >= 8
  and Gemfile depends on flipper-notifications >= 0,
  version solving has failed.
```
Are there any plans to upgrade the gem to be compatible with activesupport 8?

Thanks

**Comment by jdlubrano** [comment]
Hi @JuanMiguelGM 👋 .  Yes, we are planning to upgrade this gem to support Rails 8.  I'm not sure how long it may take to find bandwidth to do that work, though.  At worst, I could probably get it done before the end of the year.  In the meantime, if you would like to create a fork and just bump the dependencies in the specfile, this gem might "just work" with Rails 8.  I don't see anything in the ActiveSupport changelogs that would seem problematic.  I think most of the work in this gem itself would be setting up the necessary test suite to run against Rails 7 and Rails 8.

**Comment by JuanMiguelGM** [comment]
Hi @jdlubrano thanks for the quick response!
I'm trying locally to bump the dependencies but 2 tests are broken.
I don't have experience with gems and dependencies so I'd need some time, but instead of creating a fork, if I find bandwidth, I'd like to create a pull request, if you are ok with that, and then you can merge it or just cherry pick whatever you like.

**Comment by jdlubrano** [comment]
> if I find bandwidth, I'd like to create a pull request, if you are ok with that, and then you can merge it or just cherry pick whatever you like.

Works for me, thank you!
